project_id = "rgbvbzpouzuntmbcxmrc"

[functions.text-chat]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-video]
verify_jwt = false